name = "novel-portal"
compatibility_date = "2025-12-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "novel-4"
database_id = "13b2c132-7555-4d46-82cb-b900a7f39acb"

# （Previewでも同じDBを使うならこれも入れる）
[[env.preview.d1_databases]]
binding = "DB"
database_name = "novel-4"
database_id = "13b2c132-7555-4d46-82cb-b900a7f39acb"
